title: terraform
description: Terraform on-hands lab
template:
  repo: terraform-template
  name: terraform-on-hands
  description: Terraform practice laboratory
before:
  - type: createIssue
    title: Welcome! we're ready to start!
    body: new-issue.md
steps:
  - title: Prepare your environment
    description: Get started setting up your work environment.
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: Your first terraform file
    description: Configure your provider
    actions:
      - type: createIssue
        title: Let's create your first configuration file
        body: basic.md
    link: '{{ repoUrl }}'
    event: issues.closed
